name: Build and Deploy The Reploy CLI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - jay-khatri-action-for-deploying

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-central1-a
  DOCKER_BUILDKIT: 1
  GKE_CLUSTER: web-cluster

jobs:
  exec-client-deploy:
    name: Deploy Execution Client
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Install Nodejs
      uses: actions/setup-node@v1
      with:
        registry-url: 'https://registry.npmjs.org'

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        npm config set unsafe-perm true

    - run: |
        npm install

    - run: |
        npm run build


    - name: Upload bundle
      run: gsutil cp -r build/* gs://docs.getreploy.com
